### ISSUE TITLE
Download/Export bugfixes

### ISSUE THREAD

**Issue by jo-chemla** [Iconem/historical-satellite#13]
```[tasklist]
### Tasks
- [x] export bugs when using side split
- [x] download only works for planet, not other TMS
- [x] allow export of composited render, with blendingModes
```
