### ISSUE TITLE
Intégration collection date dans historical-satellite

### ISSUE THREAD

**Issue by jo-chemla** [Iconem/historical-satellite#2]
See the [wiki post](https://wiki.iconem.com/en/research/photogrammetry/Satellite-Airborne-2D-3D-data-providers#collection-date)

Also useful; EsriWayback integrated within [iD OSM Editor](https://github.com/OpenHistoricalMap/iD/pull/181) from OpenHistoricalMap as well as within [facebook/Rapid](https://github.com/facebook/Rapid/issues/1209) and [here](https://github.com/facebook/Rapid/pull/1351), both of which are tools really worth digging into

### Tasks
- [x] Bing : [1](https://zoom.earth/) seem to use bing imagery. Otherwise, [2](http://mvexel.dev.openstreetmap.org/bing/) outdated, prefer direct http header inspection as seen [here](https://philippgaertner.github.io/2018/11/microsoft-bing-maps/) look for response header param `x-ve-tilemeta-capturedatesrange | 1/1/1999-12/31/2003`
- [x] ESRI : [historical ESRI wayback archive](https://livingatlas.arcgis.com/wayback/), can look for collection date on [1](https://www.arcgis.com/home/item.html?id=10df2279f9684e4a9f6a7f08febac2a9) or [2](http://www.arcgis.com/home/webmap/viewer.html?webmap=c1c2090ed8594e0193194b750d0d5f83)
- [ ] Mapbox relies on the Maxar basemap, so could use their STAC or WxS API endpoint to determine date of each tile or footprint of image mosaicked.
- [ ] Google Earth Pro : Look for the date (bottom left) of GEarth software or timeline (when activated)
- [ ] HERE Maps : Unknown
- [ ] Mapquest : [1](http://a.tiles.mapbox.com/v4/mapbox.satellite/page.html?access_token=pk.eyJ1IjoibWFwcXVlc3QiLCJhIjoiY2Q2N2RlMmNhY2NiZTRkMzlmZjJmZDk0NWU0ZGJlNTMifQ.mPRiEubbajc6a5y9ISgydg#17/36.51005/43.22682)

**Comment by jo-chemla** [comment]
Once done for most providers, it might be interesting to display the date on the timeline slider rather than as text - with a solo point or min/max ranges.
