### ISSUE TITLE
TODO tracking - historical-sat 

### ISSUE THREAD

**Issue by jo-chemla** [Iconem/historical-satellite#4]
### Mini Tasks not in issues
- [x] geocoder `flyTo.duration` à monter de 0 à 100ms sur historical
- [x] niveau de zoom 15 pour les search latlon
- [x] latlon localGeocoder default zoom: 17?
- [x] color-burn en 3è place dans les blending modes
- [x] le geocoder mapbox est parfois assez mauvais et retourne souvent des noms de rues plutôt que des sites, ça vaut le coup de set `options.addressAccuracy: "place"` sur le mapboxgeocoder
- [x] mini-bug, le globe 3d est utilisé par défaut (visible à low-zoom-levels) quand sélection de la basemap mapbox, du à la projection:globe. On devrait surement corriger ça en passant aux deux components Map une prop  `projection: 'naturalEarth' préférable ou 'mercator' si naturalearth ne fonctionne pas`, probablement en le mettant directement dans l'objet `sharedMapsProps`
- [x] ↔️ Button to swap left/right sources
